//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootCampDB_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Evaluation_Feedback = new HashSet<Evaluation_Feedback>();
        }
    
        public int Candidate_Id { get; set; }
        public string Candidate_Name { get; set; }
        public string Phone_no { get; set; }
        public string Resume { get; set; }
        public string Comments { get; set; }
        public string isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation_Feedback> Evaluation_Feedback { get; set; }
    }
}
